apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-d
spec:
  template:
    metadata:
      name: redis-app
      labels:
        name: redis-app

    spec:
      containers:
        - name: redis-app
          image: redis:latest
  selector:
    matchLabels:
      name: redis-app
